version: "3.8"

services:
  local-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: shopping_mall_db
      MYSQL_ROOT_PASSWORD: dbadmin
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql