version: "3.8"

services:
  local-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: shopping_mall_db
      MYSQL_ROOT_PASSWORD: dbadmin
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    container_name: local-db

  local-redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    command: redis-server --port 6379
    container_name: local-redis

  test-aws:
    image: localstack/localstack:1.2
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PORT_WEB_UI=4567
      - AWS_DEFAULT_REGION=ap-northeast-2
      - USE_SSL=0
    ports:
      - 4566:4566
    volumes:
      - ./s3data:/tmp/localstack
      - ./script/create-local-s3-bucket.sh:/docker-entrypoint-initaws.d/init-aws.sh
    container_name: test-aws
