version: "3.8"

services:
  local-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: shopping_mall_db
      MYSQL_ROOT_PASSWORD: dbadmin
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    container_name: local-db

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data
      - ./script/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: local-mongo

  local-redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    command: redis-server --port 6379
    container_name: local-redis